-- PIBR Morumbi V3.2 — integração do formulário público de oração com o painel.
-- Esta migração já foi aplicada no projeto Supabase conectado em 17/08/2026.

alter table public.pibr_prayer_requests
  add column if not exists category text,
  add column if not exists age smallint,
  add column if not exists location_text text,
  add column if not exists church_info text,
  add column if not exists wants_contact boolean not null default false,
  add column if not exists cell_info text,
  add column if not exists source text not null default 'panel';

alter table public.pibr_prayer_requests
  drop constraint if exists pibr_prayer_requests_age_check;
alter table public.pibr_prayer_requests
  add constraint pibr_prayer_requests_age_check check (age is null or age between 1 and 120);

create table if not exists app_private.pibr_public_form_rate_limits (
  id bigint generated by default as identity primary key,
  form_name text not null,
  client_ip text not null,
  created_at timestamptz not null default now()
);
create index if not exists pibr_public_form_rate_limits_lookup_idx
  on app_private.pibr_public_form_rate_limits (form_name, client_ip, created_at desc);

create or replace function public.pibr_submit_prayer_request(
  p_requester_name text,
  p_requester_phone text,
  p_message text,
  p_category text default null,
  p_age integer default null,
  p_location_text text default null,
  p_church_info text default null,
  p_wants_contact boolean default false,
  p_cell_info text default null,
  p_honeypot text default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id uuid;
  v_headers jsonb := coalesce(nullif(current_setting('request.headers', true), ''), '{}')::jsonb;
  v_client_ip text;
  v_recent_count integer;
begin
  if nullif(btrim(coalesce(p_honeypot, '')), '') is not null then raise exception 'Invalid submission'; end if;
  if char_length(btrim(coalesce(p_requester_name, ''))) < 2 or char_length(btrim(coalesce(p_requester_name, ''))) > 120 then raise exception 'Nome inválido'; end if;
  if char_length(btrim(coalesce(p_requester_phone, ''))) < 8 or char_length(btrim(coalesce(p_requester_phone, ''))) > 30 then raise exception 'WhatsApp inválido'; end if;
  if char_length(btrim(coalesce(p_message, ''))) < 5 or char_length(btrim(coalesce(p_message, ''))) > 3000 then raise exception 'Pedido inválido'; end if;
  if p_category is not null and char_length(p_category) > 80 then raise exception 'Área inválida'; end if;
  if p_age is not null and (p_age < 1 or p_age > 120) then raise exception 'Idade inválida'; end if;
  if p_location_text is not null and char_length(p_location_text) > 180 then raise exception 'Localização inválida'; end if;
  if p_church_info is not null and char_length(p_church_info) > 280 then raise exception 'Informação de igreja inválida'; end if;
  if p_cell_info is not null and char_length(p_cell_info) > 180 then raise exception 'Informação de célula inválida'; end if;

  v_client_ip := split_part(coalesce(v_headers->>'x-forwarded-for', 'unknown'), ',', 1);
  v_client_ip := left(btrim(coalesce(nullif(v_client_ip, ''), 'unknown')), 80);
  delete from app_private.pibr_public_form_rate_limits where created_at < now() - interval '2 days';
  select count(*) into v_recent_count from app_private.pibr_public_form_rate_limits
   where form_name='prayer' and client_ip=v_client_ip and created_at >= now() - interval '10 minutes';
  if v_recent_count >= 5 then raise exception 'Muitas tentativas. Aguarde alguns minutos e tente novamente.'; end if;
  insert into app_private.pibr_public_form_rate_limits(form_name, client_ip) values ('prayer', v_client_ip);

  insert into public.pibr_prayer_requests(
    requester_name, requester_phone, message, category, age, location_text,
    church_info, wants_contact, cell_info, status, is_private,
    assigned_leader_id, admin_notes, source
  ) values (
    left(btrim(p_requester_name),120), left(btrim(p_requester_phone),30), btrim(p_message),
    nullif(left(btrim(coalesce(p_category,'')),80),''), p_age,
    nullif(left(btrim(coalesce(p_location_text,'')),180),''),
    nullif(left(btrim(coalesce(p_church_info,'')),280),''), coalesce(p_wants_contact,false),
    nullif(left(btrim(coalesce(p_cell_info,'')),180),''), 'new'::public.pibr_prayer_status,
    true, null, null, 'site'
  ) returning id into v_id;
  return v_id;
end;
$$;

revoke all on function public.pibr_submit_prayer_request(text,text,text,text,integer,text,text,boolean,text,text) from public;
revoke all on function public.pibr_submit_prayer_request(text,text,text,text,integer,text,text,boolean,text,text) from authenticated;
grant execute on function public.pibr_submit_prayer_request(text,text,text,text,integer,text,text,boolean,text,text) to anon;
revoke select, insert, update, delete on table public.pibr_prayer_requests from anon;
